version: '3'
services:
  go:
    build: ./docker
    container_name: go
    stdin_open: true
    tty: true
    command: "go run src/main.go"
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
  # db:
  #   image: postgres:9.5.9
  #   # ports:
  #   #   - "5432:5432"
  #   volumes:
  #     - ./volumes/postgresql:/var/lib/postgresql/data:delegated
